name: Publish to Comfy Registry

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ 'pyproject.toml' ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish to Comfy Registry
        uses: Comfy-Org/publish-node-action@main
        with:
          personal_access_token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
