name: Publish to Comfy Registry

on:
  push:
    branches: [ main ]
    paths: [ 'pyproject.toml' ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish to Comfy Registry
        uses: ComfyNodePRs/publish-node-action@v1
        with:
          registry-access-token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
